routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PaymentRequestController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->prefix('/payment-requests')->name('payments.')->group(function () {

    Route::get('/', [PaymentRequestController::class, 'index'])->name('index');
    Route::get('/create', [PaymentRequestController::class, 'create'])->name('create');
    Route::get('/{paymentRequest}', [PaymentRequestController::class, 'show'])->name('show');
    Route::post('/', [PaymentRequestController::class, 'store'])->name('store');
    Route::get('/{paymentRequest}/edit', [PaymentRequestController::class, 'edit'])->name('edit');
    Route::put('/{paymentRequest}', [PaymentRequestController::class, 'update'])->name('update');
    Route::delete('/{paymentRequest}', [PaymentRequestController::class, 'destroy'])->name('destroy');
    Route::post('/{paymentRequest}/approved', [PaymentRequestController::class, 'approved'])->name('approved');
    Route::post('/{paymentRequest}/denied', [PaymentRequestController::class, 'denied'])->name('denied');
});




require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/payments/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Requests') }}
        </h2>
    </x-slot>


    <div class="mt-1 md:grid md:grid-cols-4 md:gap-6 max-w-5xl mx-auto">
        {{-- <div class="mt-5 md:mt-0 md:col-span-1">
            <div class="px-4 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">New Payment Request</h3>
                <p class="mt-1 text-sm text-gray-600">
                This information will be displayed publicly so be careful what you share.
                </p>
            </div>
        </div> --}}

        <div class="mt-5 md:mt-0 md:col-span-4">
            <form action="{{ route('payments.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="shadow sm:rounded-md sm:overflow-hidden">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">

                        <div class="grid grid-cols-6 gap-6">
                            <div class="col-span-6 sm:col-span-3">
                                <label for="title" class="input-label">{{ __('Title') }}</label>
                                <input type="text" id="title" name="title" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md @error('title') form-control-invalid @enderror" value="{{ old('title') }}" placeholder="{{ __('Title') }}">
                                @error('title')
                                    <p class="block text-red-700">
                                        {{ $message }}
                                    </p>
                                @enderror
                            </div>

                            <div class="col-span-6 sm:col-span-3">
                                <label for="price" class="input-label">{{ __('Price') }}</label>
                                <div class="relative">
                                    @if (!is_locale_fa())
                                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                            <span class="text-gray-500 sm:text-sm">
                                                $
                                            </span>
                                        </div>
                                    @endif
                                    <input @if(is_locale_fa()) dir="ltr" @endif type="text" id="price" name="price" class="@if(is_locale_fa()) pl-14 @else pl-7 @endif mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md @error('price') form-control-invalid @enderror" value="{{ old('price') }}">
                                    <div class="absolute top-2 @if(is_locale_fa()) left-0 pl-3 @else right-0 pr-3 @endif flex items-center pointer-events-none">
                                       <span class="text-gray-500 sm:text-sm" id="price-currency">
                                        @if(is_locale_fa())
                                            تومان
                                        @else     
                                            USD
                                        @endif
                                        </span>
                                    </div> 
                                    @error('price')
                                        <p class="block text-red-700">
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="mt-3">
                            <label for="description" class="input-label">{{ __('Description') }}</label>
                            <div class="mt-1">
                                <textarea type="text" id="description" name="description" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md @error('description') form-control-invalid @enderror"  placeholder="{{ __('Description') }}">{{ old('description') }}</textarea>
                            </div>
                            <p class="mt-2 text-sm text-gray-500">
                                {{ __('Brief description for your payment request.') }}
                            </p>
                            @error('description')
                                <p class="block text-red-700">
                                    {{ $message }}
                                </p>
                            @enderror
                        </div>

                        <div>
                            <label class="input-label">
                            {{ __('Document') }}
                            </label>
                            <div class="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                            <div class="space-y-1 text-center">
                                <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                <div class="flex text-sm text-gray-600">
                                <label for="file" class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                                    <span class="mx-auto">Upload a file</span>
                                    <input id="file" name="file" type="file" class="sr-only">
                                </label>
                                {{-- <p class="pl-1">or drag and drop</p> --}}
                                </div>
                                <p class="text-xs text-gray-500">
                                PNG, JPG
                                </p>
                            </div>
                            </div>
                            @error('file')
                            <p class="block text-red-700">
                                {{ $message }}
                            </p>
                            @enderror
                        </div>
                    </div>

                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <a href="{{ route('payments.index') }}" class="@if(is_locale_fa()) ml-1 @else mr-1 @endif no-underline btn bg-black hover:bg-gray-700 focus:ring-gray-500">
                            {{ __('Back to the list') }}
                        </a>
                        <button type="submit" class="btn bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500">
                        {{ __('Create') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


</x-app-layout>

resources/views/payments/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Payment Requests') }}
            </h2>
            @if (!admin())
                <a class="no-underline btn bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500" href="{{ route('payments.create') }}">{{ __('Create') }}</a>
            @endif
        </div>
    </x-slot>

    @if (session('status'))
        <!-- This example requires Tailwind CSS v2.0+ -->
        <!-- Global notification live region, render this permanently at the end of the document -->
        <div id="notification" aria-live="assertive" class="transition-opacity opacity-100 fixed inset-0 flex items-end px-4 py-6 pointer-events-none sm:p-6">
            <div class="w-full flex flex-col items-center space-y-4 sm:items-end">
            <!--
                Notification panel, dynamically insert this into the live region when it needs to be displayed

                Entering: "transform ease-out duration-300 transition"
                From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
                To: "translate-y-0 opacity-100 sm:translate-x-0"
                Leaving: "transition ease-in duration-100"
                From: "opacity-100"
                To: "opacity-0"
            -->
            <div class="max-w-sm w-full bg-green-50 shadow-lg rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 overflow-hidden">
                <div class="p-4">
                <div class="flex items-start">
                    <div class="flex-shrink-0">
                    <!-- Heroicon name: outline/check-circle -->
                    <svg class="h-6 w-6 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    </div>
                    <div class="@if(is_locale_fa()) mr-3 @else ml-3 @endif w-0 flex-1 pt-0.5">
                        <p class="text-sm font-medium text-gray-900">
                            <!-- {{ __('Successfully created!') }} -->
                            {{ __(session('status')) }}
                        </p>
                    @if (session()->has('description'))
                        <p class="mt-1 text-sm text-gray-500">
                            {{ __(session('description')) }}
                        </p>
                    @endif
                    </div>
                    <div class="@if(is_locale_fa()) mr-4 @else ml-4 @endif flex-shrink-0 flex">
                    <button onclick="hideNotification()" class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <span class="sr-only">{{ __('Close') }}</span>
                        <!-- Heroicon name: solid/x -->
                        <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                        </svg>
                    </button>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    @endif

    <div class="mt-1 flex flex-col max-w-5xl mx-auto">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                <tr>
                    @if (admin())
                        <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                            {{ __('Name') }}
                        </th>
                    @endif
                    <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                        {{ __('Title') }}
                    </th>
                    <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                        {{ __('price') }}
                    </th>
                    <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                        {{ __('Status') }}
                    </th>
                    <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                        {{ __('Last Updated') }}
                    </th>
                    @if (admin())
                        <th scope="col" class="table-col-header @if ('fa-IR' == app()->getLocale()) text-right @else text-left @endif">
                           {{ __('Action') }}
                        </th>
                    @endif
                    <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">{{ __('Show') }}</span>
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach ($payments as $payment)
                <tr class="@if ($loop->even) bg-white @else bg-gray-100 @endif">
                    @if (admin())
                        <td class="table-data font-medium text-gray-900">
                        {{ $payment->user->name }}
                        </td>
                    @endif
                    <td class="table-data text-gray-500">
                        {{ $payment->title }}
                    </td>
                    <td class="table-data text-gray-500">
                        {{ $payment->price }}
                    </td>
                    <td class="table-data text-gray-500">
                    @if ($payment->isWaiting())
                    <span class="status bg-blue-500">
                    {{ __('Waiting') }}
                    </span>
                    @elseif ($payment->isApproved())
                    <span class="status bg-green-600">
                    {{ __('Approved') }}
                    </span>
                    @else
                    <span class="status bg-red-500">
                    {{ __('Rejected') }}
                    </span>
                    @endif
                    </td>
                    <td class="table-data text-gray-500 font-medium">
                        {{ $payment->updated_at }}
                    </td>
                    <td class="table-data font-medium">
                    @if (!$payment->isApproved() && admin())
                        <form action="{{ route('payments.approved', ['paymentRequest' => $payment->id]) }}" method="POST">
                            @csrf
                            <button type="submit" class="btn-md bg-green-700 hover:bg-green-800 focus:ring-green-500">{{ __('Approve') }}</button>
                        </form>
                    @endif
                    </td>
                    <td class="table-data text-right font-medium">
                        <a href="{{ route('payments.show', ['paymentRequest' => $payment->id]) }}" class="text-indigo-600 hover:text-indigo-900">
                            {{ __('Show') }}
                        </a>
                    </td>
                </tr>
                @endforeach

                </tbody>
            </table>
            </div>
        </div>
        </div>
    </div>

    <div class="max-w-5xl mx-auto">
        {{ $payments->links('vendor.pagination.tailwind') }}
    </div>

    <script>
        function hideNotification(){
            document.querySelector("#notification").style.display = "none";
        }
    </script>


</x-app-layout>

resources/views/payments/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between align-items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Show Requests') }}
            </h2>
            <div class="justify-end">
                @if ($paymentRequest->added_at)
                <span class="no-underline btn bg-green-600 hover:bg-green-700 focus:ring-indigo-500" href="#">{{ __('Evaluated at:') }} {{ $paymentRequest->added_at }}</span>
                @endif
                <span class="no-underline btn bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500" href="{{ route('payments.create') }}">{{ __('Code:') }} {{ $paymentRequest->code }}</span>
            </div>
        </div>
    </x-slot>


    <div class="mt-1 md:grid md:grid-cols-4 md:gap-6 max-w-5xl mx-auto">
        {{-- <div class="mt-5 md:mt-0 md:col-span-1">
            <div class="px-4 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">New Payment Request</h3>
                <p class="mt-1 text-sm text-gray-600">
                This information will be displayed publicly so be careful what you share.
                </p>
            </div>
        </div> --}}

        <div class="mt-5 md:mt-0 md:col-span-4">
            <form action="{{ route('payments.denied', ['paymentRequest' => $paymentRequest->id]) }}" method="POST">
                <div class="shadow sm:rounded-md sm:overflow-hidden">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                        <div class="grid grid-cols-6 gap-6">
                            <div class="col-span-6 sm:col-span-3">
                                <label for="title" class="input-label">{{ __('Title') }}</label>
                                <div id="title" type=text class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    {{ $paymentRequest->title }}
                                </div>
                            </div>

                            <div class="col-span-6 sm:col-span-3">
                                <label for="price" class="input-label">{{ __('Price') }}</label>
                                <div class="relative mt-1">
                                @if (!is_locale_fa())
                                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                        <span class="text-gray-500 sm:text-sm">
                                            $
                                        </span>
                                    </div>
                                @endif
                                <div @if(is_locale_fa()) dir="ltr" @endif type="text" id="price" class="@if(is_locale_fa()) pl-14 @else pl-7 @endif mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    {{ $paymentRequest->price }}
                                </div>
                                <div class="absolute inset-y-0 @if(is_locale_fa()) left-0 pl-3 @else right-0 pr-3 @endif flex items-center pointer-events-none">
                                    <span class="text-gray-500 sm:text-sm" id="price-currency">
                                    @if(is_locale_fa())
                                        تومان
                                    @else     
                                        USD
                                    @endif
                                    </span>
                                </div> 
                            </div>
                            </div>
                        </div>

                        <div class="mt-3">
                            <label for="description" class="input-label">{{ __('Description') }}</label>
                            <div class="mt-1">
                                <div type="text" id="description" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md">{{ $paymentRequest->description }}
                                </div>
                            </div>
                        </div>

                        <div>
                            <label class="input-label">
                            {{ __('Document') }}
                            </label>
                            <div class="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                                <img src="{{ asset('storage').'/'.$paymentRequest->file_path }}">
                            </div>
                        </div>

                        @if ($paymentRequest->admin_note && Auth::user()->isUser())
                            <div>
                                <label for="Rejection" class="input-label">{{ __('Rejection Cause') }}</label>
                                <div type="text" id="Rejection" name="rejection" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-300 rounded-md">
                                    {{ $paymentRequest->admin_note }}
                                </div>
                            </div>
                        @endif

                        @if (admin())
                        <div>
                            <label for="Rejection" class="input-label">{{ __('Rejection Cause') }}</label>
                            <input type="text" id="Rejection" name="rejection" class="mt-1 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-300 rounded-md @error('rejection') form-control-invalid @enderror" value="{{ $paymentRequest->admin_note }}">
                            @error('rejection')
                            <p class="text-red-700">{{ $message }}</p>
                            @enderror
                            @csrf
                            <button type="submit" class="mt-2 btn bg-red-700 hover:bg-red-800 focus:ring-red-500">{{ __('Reject') }}</button>
                        </div>
                        @endif
                    </div>
                </div>
            </form>

            <div class="flex justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                <a href="{{ route('payments.index') }}" class="@if(is_locale_fa()) ml-2 @else mr-2 @endif no-underline btn bg-black hover:bg-gray-700 focus:ring-gray-500">
                    {{ __('Back to the list') }}
                </a>

                @if (Auth::user()->isUser() && $paymentRequest->isWaiting())
                    <a href="{{ route('payments.edit', ['paymentRequest' => $paymentRequest->id]) }}" class="@if(is_locale_fa()) ml-2 @else mr-2 @endif no-underline btn bg-blue-700 hover:bg-blue-800 focus:ring-blue-500">
                    {{ __('Edit') }}
                    </a>

                    <form action="{{ route('payments.destroy', ['paymentRequest' => $paymentRequest->id]) }}" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn bg-red-700 hover:bg-red-800 focus:ring-red-500">{{ __('Delete') }}</button>
                    </form>
                @endif

                @if (admin())
                    <form action="{{ route('payments.approved', ['paymentRequest' => $paymentRequest->id]) }}" method="POST">
                        @csrf
                        <button type="submit" class="btn bg-green-700 hover:bg-green-800 focus:ring-green-500">{{ __('Approve') }}</button>
                    </form>
                @endif
            </div>
        </div>
    </div>


</x-app-layout>